In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('/Users/raihan/Brototype/Dataset/ML/salary_data.csv')

In [3]:
df.head()

YearsExperience  Salary
0              1.1   39343
1              1.3   46205
2              1.5   37731
3              2.0   43525
4              2.2   39891

In [4]:
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [5]:
from sklearn.linear_model import Ridge
from sklearn.model_selection import train_test_split

In [6]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=0)

In [7]:
X_train

array([[ 5.3],
       [ 7.9],
       [ 2.9],
       [ 5.1],
       [ 3.2],
       [ 4.5],
       [ 8.2],
       [ 6.8],
       [ 1.3],
       [10.5],
       [ 3. ],
       [ 2.2],
       [ 5.9],
       [ 6. ],
       [ 3.7],
       [ 3.2],
       [ 9. ],
       [ 2. ],
       [ 1.1],
       [ 7.1],
       [ 4.9],
       [ 4. ]])

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit_transform(X_train)

array([[ 1.59814143e-01],
       [ 1.19860607e+00],
       [-7.99070713e-01],
       [ 7.99070713e-02],
       [-6.79210106e-01],
       [-1.59814143e-01],
       [ 1.31846668e+00],
       [ 7.59117177e-01],
       [-1.43832728e+00],
       [ 2.23739800e+00],
       [-7.59117177e-01],
       [-1.07874546e+00],
       [ 3.99535356e-01],
       [ 4.39488892e-01],
       [-4.79442428e-01],
       [-6.79210106e-01],
       [ 1.63809496e+00],
       [-1.15865253e+00],
       [-1.51823435e+00],
       [ 8.78977784e-01],
       [ 3.54858681e-16],
       [-3.59581821e-01]])

In [9]:
X_train

array([[ 5.3],
       [ 7.9],
       [ 2.9],
       [ 5.1],
       [ 3.2],
       [ 4.5],
       [ 8.2],
       [ 6.8],
       [ 1.3],
       [10.5],
       [ 3. ],
       [ 2.2],
       [ 5.9],
       [ 6. ],
       [ 3.7],
       [ 3.2],
       [ 9. ],
       [ 2. ],
       [ 1.1],
       [ 7.1],
       [ 4.9],
       [ 4. ]])

In [10]:
sc.transform(X_test)

array([[-1.35842021],
       [ 2.15749092],
       [-0.31962829],
       [-0.39953536],
       [ 1.83786264],
       [ 1.51823435],
       [ 1.87781617],
       [-0.35958182]])

In [11]:
model = Ridge(alpha=1.0)

In [12]:
model.fit(X_train,y_train)

Ridge()

In [13]:
y_pred = model.predict(X_test)

In [14]:
y_pred

array([ 41285.98631321, 123232.84526725,  65497.55827691,  63635.12966431,
       115783.13081689, 108333.41636652, 116714.34512318,  64566.34397061])

In [15]:
from sklearn.metrics import mean_squared_error,r2_score

In [16]:
mse = mean_squared_error(y_test,y_pred)

In [17]:
mse

22570641.556396

In [18]:
coefficients = model.coef_
intercept = model.intercept_

In [19]:
coefficients


array([9312.14306296])

In [20]:
intercept

27317.771718772514

In [21]:
model.predict([[2]])

array([45942.05784469])

In [22]:
r2 = r2_score(y_test,y_pred)

In [23]:
r2

0.977760519315693